// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQx_1cO6S8jS4dp6sv_3022W3A_RGwG48',
    appId: '1:1007202939310:web:319515d82e0fa8835c183f',
    messagingSenderId: '1007202939310',
    projectId: 'smart-shower-head-bfcc9',
    authDomain: 'smart-shower-head-bfcc9.firebaseapp.com',
    databaseURL: 'https://smart-shower-head-bfcc9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shower-head-bfcc9.appspot.com',
    measurementId: 'G-D2J7RB64DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArw6pCYLCGLghpdhfh4hnoMY6b7i-jzis',
    appId: '1:1007202939310:android:06f3e9faac632b135c183f',
    messagingSenderId: '1007202939310',
    projectId: 'smart-shower-head-bfcc9',
    databaseURL: 'https://smart-shower-head-bfcc9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shower-head-bfcc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbcWLs7HLLy32potDdy1xFdE-FouwJVA',
    appId: '1:1007202939310:ios:49289a787f808f2d5c183f',
    messagingSenderId: '1007202939310',
    projectId: 'smart-shower-head-bfcc9',
    databaseURL: 'https://smart-shower-head-bfcc9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shower-head-bfcc9.appspot.com',
    iosClientId: '1007202939310-9u0dclk6tf91320k7eirq38ugeiuo832.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShowerHead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACbcWLs7HLLy32potDdy1xFdE-FouwJVA',
    appId: '1:1007202939310:ios:49289a787f808f2d5c183f',
    messagingSenderId: '1007202939310',
    projectId: 'smart-shower-head-bfcc9',
    databaseURL: 'https://smart-shower-head-bfcc9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shower-head-bfcc9.appspot.com',
    iosClientId: '1007202939310-9u0dclk6tf91320k7eirq38ugeiuo832.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShowerHead',
  );
}
